import {
  AtSign,
  Briefcase,
  Contact,
  Database,
  DollarSign,
  FileText,
  Fingerprint,
  Flame,
  Ghost,
  GitBranch,
  Github,
  Globe,
  Headphones,
  Instagram,
  Key,
  LockKeyhole,
  type LucideIcon,
  MailCheck,
  MessageCircle,
  Music,
  Phone,
  Scan,
  Search,
  ShieldAlert,
  Skull,
  Terminal,
  Tv,
  Twitter,
  UserSearch,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "mail-check": MailCheck,
  "shield-alert": ShieldAlert,
  "lock-keyhole": LockKeyhole,
  skull: Skull,
  "file-text": FileText,
  "user-search": UserSearch,
  github: Github,
  gitlab: GitBranch,
  twitter: Twitter,
  instagram: Instagram,
  music: Music,
  "message-circle": MessageCircle,
  "at-sign": AtSign,
  tv: Tv,
  headphones: Headphones,
  flame: Flame,
  "dollar-sign": DollarSign,
  briefcase: Briefcase,
  key: Key,
  phone: Phone,
  search: Search,
  scan: Scan,
  fingerprint: Fingerprint,
  globe: Globe,
  terminal: Terminal,
  database: Database,
  contact: Contact,
  ghost: Ghost,
};

export function getModuleIcon(iconName: string): LucideIcon {
  return iconMap[iconName] ?? Search;
}
