# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider :virtualbox do |vb|
    vb.name = "iKy"
    vb.memory = "4096"
  end
  config.vm.hostname = "iKy"

  config.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 6379, host: 6379, host_ip: "127.0.0.1"

  config.vm.provision "shell", path: "provision.sh", privileged: false
  config.vm.provision "shell", path: "stop_iKy.sh", privileged: false, run: 'always'
  config.vm.provision "shell", path: "start_iKy.sh", privileged: false, run: 'always'
  config.vm.provision "shell", path: "checks.sh", privileged: false, run: 'always'
  config.vm.provision "file", source: "scripts", destination: "$HOME/scripts"
end
