from celery import Celery

app = Celery('celery_config', broker='redis://localhost:6379/0',
             backend='redis://localhost:6379/0',
             include=['modules.github.github_tasks',
                      'modules.gitlab.gitlab_tasks',
                      'modules.leaks.leaks_tasks',
                      'modules.keybase.keybase_tasks',
                      'modules.twitter.twitter_tasks',
                      'modules.linkedin.linkedin_tasks',
                      'modules.username.username_tasks',
                      'modules.fullcontact.fullcontact_tasks',
                      'modules.emailrep.emailrep_tasks',
                      'modules.socialscan.socialscan_tasks',
                      'modules.search.search_tasks',
                      'modules.instagram.instagram_tasks',
                      'modules.tiktok.tiktok_tasks',
                      'modules.sherlock.sherlock_tasks',
                      'modules.holehe.holehe_tasks',
                      'modules.tinder.tinder_tasks',
                      'modules.skype.skype_tasks',
                      'modules.venmo.venmo_tasks',
                      'modules.darkpass.darkpass_tasks',
                      'modules.tweetiment.tweetiment_tasks',
                      'modules.reddit.reddit_tasks',
                      'modules.peopledatalabs.peopledatalabs_tasks',
                      'modules.leaklookup.leaklookup_tasks',
                      'modules.twitter_comparison.twitter_info_tasks',
                      'modules.twitter_comparison.twitter_comp_tasks',
#                       'modules.twint.twint_tasks',
                      'modules.spotify.spotify_tasks',
                      'modules.twitch.twitch_tasks',
                      'modules.mastodon.mastodon_tasks',
                      'modules.dorks.dorks_tasks'
                      ])
